name: albumlog
description: "App that scrapes album data from Discogs and allows users to save their favorite albums."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  # API communication
  http: ^0.13.5
  # Local saved albums storage
  shared_preferences: ^2.0.15
  path_provider: ^2.1.6

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
